include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    #Errors
    always_declare_return_types:
      severity: error
    annotate_overrides:
      severity: error
    avoid_catches_without_on_clauses:
      severity: error
    avoid_catching_errors:
      severity: error
    avoid_double_and_int_checks:
      severity: error
    avoid_empty_else:
      severity: error
    avoid_equals_and_hash_code_on_mutable_classes:
      severity: error
    avoid_field_initializers_in_const_classes:
      severity: error
    avoid_init_to_null:
      severity: error
    avoid_js_rounded_ints:
      severity: error
    avoid_positional_boolean_parameters:
      severity: error
    avoid_relative_lib_imports:
      severity: error
    avoid_return_types_on_setters:
      severity: error
    avoid_returning_null_for_void:
      severity: error
    avoid_void_async:
      severity: error
    await_only_futures:
      severity: error
    cancel_subscriptions:
      severity: error
    close_sinks:
      severity: error
    conditional_uri_does_not_exist:
      severity: error
    implementation_imports:
      severity: error
    invalid_runtime_check_with_js_interop_types:
      severity: error
    null_check_on_nullable_type_parameter:
      severity: error
    null_closures:
      severity: error
    recursive_getters:
      severity: error

    # Warnings
    always_put_control_body_on_new_line:
      severity: warning
    always_put_required_named_parameters_first:
      severity: warning
    avoid_bool_literals_in_conditional_expressions:
      severity: warning
    avoid_escaping_inner_quotes:
      severity: warning
    camel_case_extensions:
      severity: warning
    camel_case_types:
      severity: warning
    collection_methods_unrelated_type:
      severity: warning
    combinators_ordering:
      severity: warning
    comment_references:
      severity: warning
    constant_identifier_names:
      severity: warning
    curly_braces_in_flow_control_structures:
      severity: warning
    directives_ordering:
      severity: warning
    discarded_futures:
      severity: warning
    empty_catches:
      severity: warning
    empty_constructor_bodies:
      severity: warning
    empty_statements:
      severity: warning
    file_names:
      severity: warning
    join_return_with_assignment:
      severity: warning
    literal_only_boolean_expressions:
      severity: warning
    matching_super_parameters:
      severity: warning
    no_literal_bool_comparisons:
      severity: warning
    non_constant_identifier_names:
      severity: warning
    noop_primitive_operations:
      severity: warning
    omit_local_variable_types:
      severity: warning
    package_names:
      severity: warning
    package_prefixed_library_names:
      severity: warning
    prefer_adjacent_string_concatenation:
      severity: warning
    prefer_conditional_assignment:
      severity: warning
    prefer_const_constructors:
      severity: warning
    prefer_const_declarations:
      severity: warning
    prefer_const_literals_to_create_immutables:
      severity: warning
    prefer_contains:
      severity: warning
    prefer_expression_function_bodies:
      severity: warning
    prefer_final_fields:
      severity: warning
    prefer_final_in_for_each:
      severity: warning
    prefer_if_null_operators:
      severity: warning
    prefer_initializing_formals:
      severity: warning
    prefer_interpolation_to_compose_strings:
      severity: warning
    prefer_is_empty:
      severity: warning
    prefer_is_not_empty:
      severity: warning
    prefer_is_not_operator:
      severity: warning
    prefer_iterable_whereType:
      severity: warning
    prefer_null_aware_method_calls:
      severity: warning
    prefer_null_aware_operators:
      severity: warning
    prefer_spread_collections:
      severity: warning
    prefer_typing_uninitialized_variables:
      severity: warning
    require_trailing_commas:
      severity: warning

    # Information
    secure_pubspec_urls: true
    sized_box_shrink_expand: true
    sort_pub_dependencies: false
    strict_top_level_inference: true
    switch_on_type: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_library_name: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    unnecessary_underscores: true
    unreachable_from_main: true
    unrelated_type_equality_checks: true
    use_colored_box: true
    use_decorated_box: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_null_aware_elements: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_in_part_of_directives: true
    void_checks: true
