name: wandrr
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  intl: any
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  http: ^1.1.0
  calendar_date_picker2: ^0.5.3
  aligned_dialog: ^0.0.7
  equatable: ^2.0.5
  dropdown_search: ^5.0.6
  fl_chart: ^0.66.0
  google_sign_in: ^6.2.1
  flutter_datetime_picker_plus: ^2.2.0
  rive: ^0.13.20
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.4.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/images/flags/
    - assets/images/tripThumbnails/
    - assets/

flutter_gen:
  output: lib/asset_manager/
  line_length: 80
  integrations:
    flutter_svg: true
