// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDks-wJ3anI-u2FBxMz_Cf3_RxKNpS6Tek',
    appId: '1:778106737436:web:89a5bd2a082afab71c20d9',
    messagingSenderId: '778106737436',
    projectId: 'wandrr-15f70',
    authDomain: 'wandrr-15f70.firebaseapp.com',
    storageBucket: 'wandrr-15f70.firebasestorage.app',
    measurementId: 'G-94XZM7CR87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsx5jESm-3PJJFeisEuxCmrNg9ke5YYs',
    appId: '1:778106737436:android:8b27ad2ddf5162891c20d9',
    messagingSenderId: '778106737436',
    projectId: 'wandrr-15f70',
    storageBucket: 'wandrr-15f70.firebasestorage.app',
  );

}