include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    # Errors
    always_declare_return_types: error
    annotate_overrides: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_double_and_int_checks: error
    avoid_empty_else: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_field_initializers_in_const_classes: error
    avoid_init_to_null: error
    avoid_js_rounded_ints: error
    avoid_positional_boolean_parameters: error
    avoid_relative_lib_imports: error
    avoid_return_types_on_setters: error
    avoid_returning_null_for_void: error
    avoid_void_async: error
    await_only_futures: error
    cancel_subscriptions: error
    collection_methods_unrelated_type: error
    close_sinks: error
    conditional_uri_does_not_exist: error
    empty_constructor_bodies: error
    empty_statements: warning
    implementation_imports: error
    invalid_runtime_check_with_js_interop_types: error
    literal_only_boolean_expressions: error
    matching_super_parameters: error
    no_literal_bool_comparisons: error
    noop_primitive_operations: error
    null_check_on_nullable_type_parameter: error
    null_closures: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    recursive_getters: error
    unused_import: error

    # Warnings
    always_put_required_named_parameters_first: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_escaping_inner_quotes: warning
    camel_case_extensions: warning
    camel_case_types: warning
    combinators_ordering: warning
    comment_references: warning
    constant_identifier_names: warning
    curly_braces_in_flow_control_structures: warning
    directives_ordering: warning
    empty_catches: warning
    file_names: warning
    join_return_with_assignment: warning
    non_constant_identifier_names: warning
    omit_local_variable_types: warning
    package_names: warning
    package_prefixed_library_names: warning
    prefer_adjacent_string_concatenation: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_contains: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_iterable_whereType: warning
    prefer_null_aware_method_calls: warning
    prefer_null_aware_operators: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning

    # Integration test overrides
    avoid_print: ignore

linter:
  rules:
    # Errors
    always_declare_return_types: true
    annotate_overrides: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_positional_boolean_parameters: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    conditional_uri_does_not_exist: true
    implementation_imports: true
    invalid_runtime_check_with_js_interop_types: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    recursive_getters: true

    # Warnings
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_escaping_inner_quotes: true
    camel_case_extensions: true
    camel_case_types: true
    collection_methods_unrelated_type: true
    combinators_ordering: true
    comment_references: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    join_return_with_assignment: true
    literal_only_boolean_expressions: true
    matching_super_parameters: true
    no_literal_bool_comparisons: true
    non_constant_identifier_names: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    package_names: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true

    # Info / stylistic rules
    avoid_print: false
    switch_on_type: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_late: true
    unnecessary_library_name: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    unnecessary_underscores: true
    unreachable_from_main: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: false
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_null_aware_elements: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_in_part_of_directives: true
    void_checks: true

